apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: minio
data:
  MINIO_BROWSER: "on"
  MINIO_IDENTITY_OPENID_DISPLAY_NAME: "Tenant Keycloak"
  MINIO_IDENTITY_OPENID_SCOPES: "openid,profile,email"
  MINIO_IDENTITY_OPENID_CLAIM_NAME: "policy"
  MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC: "on"
  MINIO_PROMETHEUS_AUTH_TYPE: "public"
  MINIO_API_CORS_ALLOW_ORIGIN: "*"
  MINIO_BOOTSTRAP_BUCKET: "dil-data"
