apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: minio
spec:
  storageClassName: longhorn-1replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
